from abc import ABC, abstractmethod
from typing import Optional
from src.domain.url import Url

class URL_Repository(ABC):
    @abstractmethod
    def save_url(self, url: str) -> int:
        """
        Save the original URL on the DB
        returns: incremental id generated by DB
        """
        pass

    def update_url_alias(self, url_id: int, alias: str)->None:
        """
        Search for url_id and then assing the generated alias
        """
        pass

    @abstractmethod
    def get_url_by_alias(self, alias: str) -> Optional[Url]:
        """
        Search by alias in the DB
        return: Complete URL if it is in DB, None if not exist
        """
        pass

